name: agro_bots
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+2
  image_picker: ^1.0.4
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.18.1
  dio: ^5.3.2  # Advanced HTTP client
  retrofit: ^4.0.3  # Type-safe HTTP client
  json_annotation: ^4.8.1  # JSON serialization
  pretty_dio_logger: ^1.3.1  # API logging
  connectivity_plus: ^4.0.2  # Network connectivity check

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.0.4
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700